import os
import re
from pathlib import Path

import re
from pathlib import Path


def dart_type_map():
    return {
        "int32": "int",
        "uint32": "int",
        "uint64": "int",
        "int64": "int",
        "string": "String",
        "bool": "bool",
        "bytes": "List<int>",
        "double": "double",
        "float": "double",
    }


def parse_proto(file_path: Path):
    content = file_path.read_text(encoding="utf-8").splitlines()

    messages = {}
    message_name = None
    fields = []

    # 普通类型过滤
    normal_type_pattern = "(" + "|".join(list(dart_type_map().keys())) + ")"
    # 组合完整正则
    normal_pattern = rf"^{normal_type_pattern}\s+\w+"

    for line in content:
        line = line.strip()

        # message 开始
        if line.startswith("message "):
            m = re.match(r"^message\s+(\w+)", line)
            if m:
                message_name = m.group(1)
                fields = []

        # 字段
        elif re.match(normal_pattern, line):
            m = re.match(r"(\w+)\s+(\w+)\s*=\s*\d+;\s*(?://\s*(.*))?", line)
            if m:
                ftype, fname, comment = m.groups()
                fields.append((ftype, fname, comment or "", False))
        # 类数组
        elif re.match(r"^(repeated\s+)?(\w+)\s+(\w+)", line):
            m = re.match(
                r"(repeated\s+)?(\w+)\s+(\w+)\s*=\s*\d+;\s*(?://\s*(.*))?", line
            )
            if m:
                repeated, ftype, fname, comment = m.groups()
                is_repeated = repeated is not None
                fields.append((ftype, fname, comment or "", is_repeated))

        # message 结束
        elif line.startswith("}"):
            if message_name:
                messages[message_name] = fields
                message_name = None
                fields = []

    return messages


def to_camel_case(s: str) -> str:
    if "_" not in s:
        # 没有下划线，首字母小写
        return s[0].lower() + s[1:] if s else s

    parts = s.split("_")
    # 第一个单词小写
    first = parts[0].lower()
    # 后续单词首字母大写，其余保持小写
    others = [p.capitalize() for p in parts[1:]]
    return first + "".join(others)


def to_dart_class(message_name, fields):
    dart_key_word_map = {"switch": "switc"}

    lines = []
    lines.append(f"@JsonSerializable(explicitToJson: true)")
    # 统一后缀，区别于protobuf文件定义
    model_sub = "MsgModel"
    class_new_Name = message_name + model_sub
    lines.append(f"class {class_new_Name} {{")

    # 字段定义
    params = []
    for ftype, fname, comment, is_repeated in fields:
        # 临时根据统一后缀判定，后面如果出现不一致情况，可以先便利一遍匹配转化字典，再执行写入
        if str(ftype).endswith("MO"):
            ftype += model_sub
            
        if is_repeated:
            type_temp = dart_type_map().get(ftype, ftype)
            dart_type = f"List<{type_temp}>?"
        else:
            dart_type = dart_type_map().get(ftype, ftype) + "?"

        camel_name = to_camel_case(fname)

        camel_name = dart_key_word_map.get(camel_name, camel_name)
        params.append(camel_name)

        if comment:
            lines.append(f"  // {comment}")
        # default_value = ", defaultValue: 0" if dart_type == "int?" else ""
        default_value = ""
        lines.append(f"  @JsonKey(name: '{fname}'{default_value})")
        lines.append(f"  final {dart_type} {camel_name};")

    # 构造函数
    params = ", ".join([f"this.{f}" for f in params])
    lines.append(f"  {class_new_Name}({params});\n")

    # fromJson & toJson
    lines.append(
        f"  factory {class_new_Name}.fromMsgMo({message_name} mo) =>{class_new_Name}.fromJson(mo.toProto3Json() as Map<String, dynamic>);\n"
    )
    # fromJson & toJson
    lines.append(f"  factory {class_new_Name}.fromJson(Map<String, dynamic> json) =>")
    lines.append(f"      _${class_new_Name}FromJson(json);\n")
    lines.append(f"  Map<String, dynamic> toJson() => _${class_new_Name}ToJson(this);")

    lines.append("}")
    return "\n".join(lines)


if __name__ == "__main__":
    proto_file = input("输入.proto的文件地址:")
    proto_file = proto_file.removeprefix("'")
    proto_file = proto_file.removesuffix("'")
    file_path = Path(proto_file)
    messages = parse_proto(file_path)

    dart_classes = []
    for msg, fields in messages.items():
        dart_classes.append(to_dart_class(msg, fields))

    file_header = (
        "// DO NOT EDIT. \n//This is code generated by : python /scripts/protobuf_2_model.py\n// ignore_for_file: file_names\nimport 'package:json_annotation/json_annotation.dart';\nimport'"
        + file_path.stem
        + ".pb.dart';\n\npart '"
        + file_path.stem
        + ".g.dart';\n\n"
    )

    dart_code = "\n\n".join(dart_classes)

    out_file = file_path.with_suffix(".dart")
    out_file.write_text(file_header + dart_code, encoding="utf-8")
    os.system(f"dart format {out_file}")
